yolo_model:

  config_file:
    name: yolo-obj.cfg
  weight_file:
    name: yolo-obj_final.weights
    # name: yolo-obj_5000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Litters
      - Non-litters
